### ISSUE TITLE
Typeface caching

### ISSUE THREAD

**Issue by afollestad** [jahirfiquitiva/TextDrawable#1]
At https://github.com/jahirfiquitiva/TextDrawable/blob/master/library/src/main/java/jahirfiquitiva/libs/textdrawable/TextDrawable.kt#L191, a Typeface object is allocated for every `TextDrawable` instance. These instances are expensive and should be statically cached.

**Comment by jahirfiquitiva** [comment]
Thanks for the feedback. I actually meant to create this repo just for the sake of updating dependencies and code and few things here and there.

I'd like to implement your suggestion, but I'm not quite sure about how to do it properly.

Would creating a static instance (in a `companion object`) be enough? Or would you mind helping with an explanation or even a PR?

Thanks in advance.
