### ISSUE TITLE
how to Set height and width of textdrawable 

### ISSUE THREAD

**Issue by AdilBelim** [jahirfiquitiva/TextDrawable#3]
.beginConfig()  not accessale 

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version.

### Device/App info:
 - TextDrawable Version: `?`
 - Android version: `?`
 - Device Manufacturer: `?`
 - Device Name: `?`

### Reproduction Steps
1.
2.
3.

### Code and/or Logs

```kotlin
println("Hello, world!")
```

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.package.name.HelloWorld
    at com.package.name.HelloWorld$ThisIsNotARealLog
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```

**Comment by jahirfiquitiva** [comment]
use the xml properties or the corresponding methods like with any other view
https://github.com/jahirfiquitiva/TextDrawable#1-create-simple-tile

<blockquote><img src="https://avatars2.githubusercontent.com/u/10360816?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/jahirfiquitiva/TextDrawable">jahirfiquitiva/TextDrawable</a></strong></div><div>Contribute to jahirfiquitiva/TextDrawable development by creating an account on GitHub.</div></blockquote>
